-- Types permissions of the system
INSERT INTO bandsync.types_permissions (name) VALUES 
('Integrantes'),
('Repertorios'),
('Eventos'),
('Artistas'),
('Canciones'),
('Roles y permisos'),
('Géneros musicales'),
('Roles musicales'),
('Banda');  

-- Permissions of the system
INSERT INTO bandsync.permissions (name, type_permission_id) VALUES 
('Visualizar integrantes', 1), 
('Agregar integrante', 1),
('Modificar integrante', 1),
('Eliminar integrante', 1),
('Agregar repertorio', 2),
('Modificar repertorio', 2),
('Eliminar repertorio', 2),
('Agregar evento', 3),
('Modificar evento', 3),
('Eliminar evento', 3),
('Agregar artista', 4),
('Modificar artista', 4),
('Eliminar artista', 4),
('Agregar cancion', 5),
('Modificar cancion', 5),
('Eliminar cancion', 5),
('Visualizar roles y permisos', 7),
('Asignar rol', 7),
('Agregar rol', 7),
('Modificar rol', 7),
('Eliminar rol', 7),
('Agregar género musical', 8),
('Modificar género musical', 8),
('Eliminar género musical', 8),
('Agregar rol musical', 9),
('Modificar rol musical', 9),
('Eliminar rol musical', 9),
("Editar Banda", 10),
("Eliminar Banda", 10);
